# Generated by Django 4.2.30 on 2026-09-04 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='score',
            field=models.IntegerField(default=1, verbose_name='Score'),
        ),
    ]
